### ISSUE TITLE
Failure to use the API

### ISSUE THREAD

**Issue by zjemily** [qhkm/gowhisper-releases#1]
Unsure why, but I don't seem to be able to use the API anymore, but can use models locally fine. I updated to the latest windows x64 build but it throws an error when trying to update from the app with a 404 error. I also lose access to the space bar when this happens, getting taken by the app from there for playing/pausing a transcribed audio file until the error message is clicked, which might confuse some users. I did report the errors from the offered dialog. Is it possible that the missing windows build with the latest release, which seems to only have the mac version, is what's causing this? Thanks in advance for all the help!

The text from the image reads:

```
An error occurred

X Cannot download
...://github.com/qhkm/gowhisper-releases/releases/download/v1.0.9/...
status 404:

Error: Cannot download
...://github.com/qhkm/gowhisper-releases/releases/download/v1.0.9/GoWhisper-1.0.9-win...
status 404:
at ClientRequest.<anonymous> (C:\Program
Files\GoWhisper\resources\app.asar\dist\main\webpack:\GoWhisper\node_modules\b...\324)
at ClientRequest.emit (node:events:513:28)
at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:249206)
at SimpleURLLoaderWrapper.emit (node:events:513:28)

→ Ignore
→ Report
→ Exit
```

![image](https://github.com/qhkm/gowhisper-releases/assets/112844/6213bb33-cc19-408d-8cae-b2ae9d9e0363)

**Comment by qhkm** [comment]
Hi @zjemily, I apologize for the delay in responding to your message here. I've fix all the mentioned issue in the latest release so you can proceed to update the app to latest version.
